language: java
jdk:
    - openjdk8
group: stable
dist: trusty
os: linux
sudo: false
install: true
addons:
  sonarcloud:
    organization: "chetansidnal-github"
     branches:
     - ".*"
    token:
      secure: ${pass}
    github_token:
      secure: ${github-breadnbeer}
script:
  - "gradle sonarqube"
